### PR TITLE
Module 6: Application Diagrams

### PR DESCRIPTION
**Pull request by CharlieCumber**

### CODE REVIEW

**Comment by Jonesey13** [comment]
Designated Reviewer: Alex

**Review by Jonesey13 — APPROVED** [review]
I'm going to approve this as you're understood the core ideas of how these diagrams are structured.

_**However**_, there is one issue; all requests to the app controller must go through the gunicorn server (including requests from the web browser page). I'd strongly recommend correcting this issue.

**Comment by Jonesey13** [comment]
Hi Charlie,

I'm rejecting this on the grounds that this was copied from Oskar's repository. This work needs to be done independently by each learner.

Regards
Alex Jones

**Comment by JackMeadDev** [comment]
Alex and Charlie spoke during a support call and resolved the misunderstanding due to repo changes, so I'm happy to approve this

**Pull request merged**
